### ISSUE TITLE
Mobiili bugaa iOS + Safari -yhdistelmällä

### ISSUE THREAD

**Issue by LehtoneM** [laskuvarjotoimikunta/vtr#11]
iPhonella pääsee sisälle Mari.Lehtonen@laskuvarjotoimikunta.fi-osoitteella, mutta uuden vaaratilanneilmoituksen tiedot eivät päivity, vanhat eivät listaudu (selain yrittää päivittää, mutta jää rullaamaan) ja yhteisöt-valikko ei näy ollenkaan.

**Comment by savikko** [comment]
Vaikuttaa siltä, että tätä ei saada toistettua. Avataan uudestaan jos löydetään jotain merkittävää tähän lisää.
