### ISSUE TITLE
Ilmoitus voidaan lähettää ilman koulutusvaihe/lisenssi -valintaa

### ISSUE THREAD

**Issue by KimmoP** [laskuvarjotoimikunta/vtr#16]
Pakollisesta valinnasta huolimatta ilmoituksen lähettäminen on onnistunut.

**Comment by savikko** [comment]
Tuleeko siihen siis se (Valitse luokka/lisenssi) vai ihan tyhjä?

**Comment by savikko** [comment]
Vastaan itselleni, eli juuri se:
![screenshot 2016-03-14 13 59 09](https://cloud.githubusercontent.com/assets/7020294/13743858/fa223612-e9ec-11e5-8aab-5f772cd9b5d0.png)

**Comment by savikko** [comment]
En saanut toistettua tuota mitenkään itse.

Vaatii tarkempaa tutkintaa. Jos joku sen saa toistettua niin otan vastaan ohjeita.
