### ISSUE TITLE
Ilmoitus uudesta rapsasta

### ISSUE THREAD

**Issue by savikko** [laskuvarjotoimikunta/vtr#7]
Lähetetään email-ilmoitus uudesta raportista ainakin:
- LT
- SIL
- Tapahtuneen kerhon kp ja tp

Sama sähköposti ja kaikki cc:einä?

**Comment by LehtoneM** [comment]
Rapsan henkilötunnistetietojen (nimi / onko muuta?) pitäisi näkyä vain ilmoittajalle itselleen.

**Comment by savikko** [comment]
suljettu väärä issue

**Comment by savikko** [comment]
futaa.
